---
author:
  - name: Pedro Costa Ferreira
    affiliation: FGV/IBRE
    address: >
      Endereço: Rua Barão de Itambi, 60 - Botafogo
      CEP: 22231-000
    email: \email{pedro.ferreira@fgv.br}
    url: http://portalibre.fgv.br/
  - name: Talitha Speranza
    affiliation: FGV/IBRE
    address: >
      Endereço: Rua Barão de Itambi, 60 - Botafogo
      CEP: 22231-000
    email: \email{talitha.speranza@fgv.br}
    url: http://portalibre.fgv.br/ 
  - name: Fernando Teixeira
    affiliation: FGV/IBRE
    address: >
      Endereço: Rua Barão de Itambi, 60 - Botafogo
      CEP: 22231-000
    email: \email{fernando.teixeira@fgv.br}
    url: http://portalibre.fgv.br/
  - name: Daiane Marcolino
    affiliation: FGV/IBRE
    address: >
      Endereço: Rua Barão de Itambi, 60 - Botafogo
      CEP: 22231-000
    email: \email{daiane.marcolino@fgv.br}
    url: http://portalibre.fgv.br/

title:
  formatted: "Triple Filter: measuring trajectory with \\pkg{INFLATION}"
  # If you use tex in the formatted title, also supply version without
  plain:     "Triple Filter Core Inflation: measuring trajectory with Package INFLATION"
  # For running headers, if needed
  short:     "\\pkg{INFLATION}: Triple Filter Core Inflation"
abstract: > 
    The \proglang{R} package \pkg{INFLATION} provides functions to estimate the core inflation. Apart from the established exclusion (\code{core.ex}), trimming (\code{core.ma}) and double weighting (\code{core.dp}) core inflation filters the package brings a new way to estimate core inflation. In countries with higher inflation rates than traditional OECD countries, as is the case of Brazil, the existent filters do not seem to deliver much information about prices' level. To address this issue, we implement the Triple-Filter core inflation. This method consists of trimming the mean with smoothed items, perform a seasonal adjustment and finally applying moving average. This paper constitutes a companion paper to the package, introducing the core functions parameters, detailing all the core estimation techniques and providing implementation details. It also presents examples where the Triple Filter outperforms the more orthodox alternatives. 
keywords:
  # at least one keyword must be supplied
  formatted: [inflation, core, filter, "\\proglang{R}"]
  plain:     [inflation, core, filter, R]
preamble: >
  \usepackage{amsmath}
bibliography: artigo_jss.bib
output: rticles::jss_article
---

# Introduction

The core inflation measures are used by monetary authorities as a tool to measure the stabilization of prices in the economy. Despite being a popular term among policymakers, there is still no consensus on its definition nor on what it plans to capture. The consensus is that the change in the price level, despite being a monetary phenomenon, can be influenced also by non-monetary events such as, for example, bad weather conditions that make food prices more expensive because of a reduced supply of these products to the population. However, since this event is temporary, with an improving climate food prices may fall again. This transient behavior thus adds noise to the inflation rate and, therefore, the monetary authorities should be able to distinguish between a transient effect and a persistent effect on the price level when making their decisions. Given this, an inflation measure free of such interference is desirable.



This paper presents the R [@rproj] package INFLATION [@inf] which provides automatic and flexible methods to compute core inflation based on input given. The package presents three traditional ways of calculating the inflation's core and an additional one created by [@triple]


# Exclusion Core Inflation

The exclusion core inflation is easy to understand and doesn't demand much computational power which makes it a big asset. With this method we perform an exclusion of some of the prices' index items. 

## Compute time series' standard deviation

\begin{align}
\sigma_{i} = \sqrt{\frac{\sum\nolimits_{t=1}^{T}{(\pi_{i,t}-\bar{\pi}_{i}})^2}{T-1}}
\end{align}

Where:

* $\sigma_i$ is item's $i$ standard deviation
* $\pi_{i,t}$ is the item's $i$ variation in time $t$ ; 
* $\bar{\pi}_{i} = \frac{\sum_{t=1}^{T}{\pi_{i,t}}}{T}$




\begin{align}\label{equacao_mm3}
\pi_{i,t}^{TF} = \left [\left (\prod_{i=0}^{2} \frac{\pi_{i,t-i}^{AJ}}{100} + 1  \right )^{\frac{12}{3}} -1 \right ] \times 100.
\end{align}

\noindent
Where: \

$\pi_{i,t}^{AJ}$ is the core inflation seasonally adjusted (monthly percent change);\

$\pi_{i,t}^{TF}$ is the annualized Triple-Filter core.\vspace{0.3cm}

The methodology presented will be applied only to the FGV inflation rate (CPI) but can be easily replicated for any consumer price index. The first filtering methodology excludes items with extreme variations that accumulate 20\% of the lower tail and 13\% of the upper tail, leaving 67\% of the original weight of the basket of products. The estimation made by FGV/IBRE considers 20\% for the two tails. The  seasonally adjusted specifications (second filter) were set considering the complete historical series from January 1999 to March 2016. Two outliers were detected (Feb/1999 and Nov/2002), which were kept to perfect the quality of seasonal adjustment. The SARIMA(0 1 1)(1 0 0)$_{12}$ model was fitted was not applied to the processing of the data.



Don't use markdown, instead use the more precise latex commands:

* \proglang{Java}
* \pkg{plyr}
* \code{print("abc")}

# R code

Can be inserted in regular R markdown blocks.

```{r}
x <- 1:10
x
```
