# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

acum <- function(data, data2, n, m) {
    .Call('INFLATION_acum', PACKAGE = 'INFLATION', data, data2, n, m)
}

